"""Turn ``bench/results/results.json`` into ``Documentation/results.md`` and the plots.

Every plot has a table twin in ``results.md`` carrying the same numbers, so nothing is
readable from colour alone. Each plot is written twice (light and dark surface) so the
README can serve the one that matches the reader's theme. Colours follow the entity, not
the rank: Tokquay is always categorical slot 1 (blue) and the static baseline slot 2 (orange).
"""

from __future__ import annotations

from pathlib import Path

import logging

import matplotlib

matplotlib.use("Agg")
logging.getLogger("matplotlib.font_manager").setLevel(logging.ERROR)  # a missing font weight is not worth a warning
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402

PX = 0.72  # points per CSS pixel: figures are laid out at 100 dpi and saved at 200

THEMES = {
    "light": dict(surface="#fcfcfb", ink="#0b0b0b", ink2="#52514e", muted="#898781", grid="#e1e0d9", axis="#c3c2b7",
                  tokquay="#2a78d6", static="#eb6834"),  # fmt: skip
    "dark": dict(surface="#1a1a19", ink="#ffffff", ink2="#c3c2b7", muted="#898781", grid="#2c2c2a", axis="#383835",
                 tokquay="#3987e5", static="#d95926"),  # fmt: skip
}
NAMES = {"tokquay": "Tokquay (paged, continuous batching)", "static": "Static batching baseline"}
SHORT = {"tokquay": "Tokquay", "static": "Static baseline"}


# ------------------------------------------------------------------------------ data access
def _run(runs: dict, key: str) -> dict | None:
    r = runs.get(key)
    return r["summary"] if r else None


def _sweep(runs: dict) -> dict[str, dict[float, dict]]:
    """{system: {rate: summary}} from the main sweep, rates ascending."""
    out: dict[str, dict[float, dict]] = {"tokquay": {}, "static": {}}
    for key, r in runs.items():
        parts = key.split("/")
        if parts[0] == "sweep" and "#" not in key:
            out[parts[1]][r["rate"]] = r["summary"]
    return {sys: dict(sorted(d.items())) for sys, d in out.items() if d}


# ------------------------------------------------------------------------------ tables
def md_table(headers: list[str], rows: list[list[str]], text_cols: tuple[int, ...] = (0,)) -> str:
    """Markdown table; columns in ``text_cols`` are left-aligned, the rest (numbers) right-aligned."""
    align = ["---" if i in text_cols else "---:" for i in range(len(headers))]
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(align) + "|"]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def _ms(ms: float) -> str:
    return f"{ms:,.0f}"


def headline_table(static: dict, tokquay: dict) -> str:
    """The brief's Results table for one arrival rate."""
    rows = [
        ["Throughput (tok/s)", f"{static['throughput_tok_s']:.1f}", f"{tokquay['throughput_tok_s']:.1f}"],
        ["TTFT p50 / p99 (ms)", f"{_ms(static['ttft_ms']['p50'])} / {_ms(static['ttft_ms']['p99'])}",
         f"{_ms(tokquay['ttft_ms']['p50'])} / {_ms(tokquay['ttft_ms']['p99'])}"],
        ["ITL p50 / p99 (ms)", f"{static['itl_ms']['p50']:.1f} / {static['itl_ms']['p99']:.1f}",
         f"{tokquay['itl_ms']['p50']:.1f} / {tokquay['itl_ms']['p99']:.1f}"],
        ["Peak KV memory in use (MiB)", f"{static['peak_kv_allocated_mib']:.0f}", f"{tokquay['peak_kv_allocated_mib']:.0f}"],
        ["Max concurrent seqs", static["max_concurrent"], tokquay["max_concurrent"]],
    ]  # fmt: skip
    return md_table(["Metric", "Static baseline", "Tokquay"], rows)


def build_markdown(store) -> str:
    data, runs = store.data, store.data["runs"]
    meta = data["meta"]
    sweep = _sweep(runs)
    out = [
        "# Benchmark results",
        "",
        f"Generated by `python -m bench.bench report` from `bench/results/results.json` ({meta['date']}). "
        f"{meta['gpu']}, PyTorch {meta['torch']}, {meta['dtype']}"
        + (f", process pinned to CPUs {meta['cpu_affinity']}" if meta.get("cpu_affinity") else "")
        + (" at high priority" if meta.get("high_priority") else "")
        + ". Every number below comes from that file. The raw file is not committed (see `.gitignore`), so this document is "
        "the record; rerun `bench/bench.py` to regenerate it.",
        "",
    ]

    if "tokquay" in sweep and "static" in sweep:
        rates = sorted(set(sweep["tokquay"]) & set(sweep["static"]))
        n = sweep["tokquay"][rates[0]]["requests"]
        out += [f"## Arrival-rate sweep ({n} requests per run, Poisson arrivals, prompts and outputs uniform in [16, 256])", ""]
        rows = []
        for r in rates:
            s, t = sweep["static"][r], sweep["tokquay"][r]
            rows.append([f"{r:g}", f"{s['throughput_tok_s']:.1f}", f"{t['throughput_tok_s']:.1f}",
                         f"{t['throughput_tok_s'] / s['throughput_tok_s']:.2f}x"])  # fmt: skip
        out += ["### Throughput", "", md_table(["Arrival rate (req/s)", "Static (tok/s)", "Tokquay (tok/s)", "Ratio"], rows), ""]
        for r in rates:
            out += [f"### At {r:g} requests/s", "", headline_table(sweep["static"][r], sweep["tokquay"][r]), ""]

        out += ["### Latency, all rates", ""]
        rows = []
        for r in rates:
            for sysname in ("static", "tokquay"):
                s = sweep[sysname][r]
                rows.append([f"{r:g}", SHORT[sysname], _ms(s["ttft_ms"]["p50"]), _ms(s["ttft_ms"]["p99"]),
                             f"{s['itl_ms']['p50']:.1f}", f"{s['itl_ms']['p99']:.1f}"])  # fmt: skip
        out += [md_table(["req/s", "System", "TTFT p50 (ms)", "TTFT p99 (ms)", "ITL p50 (ms)", "ITL p99 (ms)"], rows, (0, 1)), ""]

        out += ["### KV memory", ""]
        rows = []
        for r in rates:
            for sysname in ("static", "tokquay"):
                s = sweep[sysname][r]
                rows.append([f"{r:g}", SHORT[sysname], f"{s['peak_kv_allocated_mib']:.0f}", f"{s['peak_kv_live_mib']:.0f}",
                             f"{100 * s['kv_utilization']:.0f}%", s["max_concurrent"]])  # fmt: skip
        out += [
            md_table(["req/s", "System", "Peak in use (MiB)", "Peak holding a token (MiB)", "Mean utilisation", "Max concurrent"], rows, (0, 1)),
            "",
            "*In use* is memory a running sequence holds (Tokquay: allocated blocks; baseline: `max_len` slots per row of the "
            "batch). *Holding a token* is the part of it that stores a cached token. Utilisation is their ratio, averaged over steps.",
            "",
        ]

        out += ["### Prefill stalls (Tokquay)", ""]
        stall_runs = [(f"{r:g}", sweep["tokquay"][r]) for r in sorted(sweep["tokquay"])]
        if _run(runs, "calibrate/tokquay"):
            stall_runs.append(("all at t=0", _run(runs, "calibrate/tokquay")))  # big prefill batches: the costly case
        rows = []
        for label, run in stall_runs:
            st = run["stalls"]
            if "prefill_step_ms" not in st or "itl_ms_stalled" not in st:
                continue
            rows.append([label, f"{100 * st['frac_gaps_stalled_by_prefill']:.0f}%",
                         f"{st['itl_ms_clean']['p50']:.0f} / {st['itl_ms_clean']['p99']:.0f}",
                         f"{st['itl_ms_stalled']['p50']:.0f} / {st['itl_ms_stalled']['p99']:.0f}",
                         f"{st['prefill_step_ms']['p50']:.0f} / {st['prefill_max_step_ms']:.0f}",
                         f"{st['prefill_padded_tokens']['p50']:.0f} / {st['prefill_padded_tokens']['p99']:.0f}",
                         f"{st['decode_step_ms']['p50']:.0f} / {st['decode_step_ms']['p99']:.0f}"])  # fmt: skip
        out += [
            md_table(["req/s", "Token gaps containing a prefill", "ITL p50 / p99, clean gaps (ms)", "ITL p50 / p99, stalled gaps (ms)",
                      "Prefill step p50 / max (ms)", "Padded tokens per prefill p50 / p99", "Decode step p50 / p99 (ms)"], rows),
            "",
            "A *stalled* gap is one between two tokens of a request during which some prefill step ran (prefill and decode never "
            "share a step, so every running sequence waits). Step times are measured, not fitted.",
            "",
        ]  # fmt: skip

    cal = {s: _run(runs, f"calibrate/{s}") for s in ("tokquay", "static")}
    if all(cal.values()):
        out += ["## Saturated throughput (all requests arrive at t=0)", "",
                md_table(["System", "Throughput (tok/s)", "Max concurrent", "Peak KV in use (MiB)"],
                         [[SHORT[s], f"{cal[s]['throughput_tok_s']:.1f}", cal[s]["max_concurrent"], f"{cal[s]['peak_kv_allocated_mib']:.0f}"]
                          for s in ("static", "tokquay")]), ""]  # fmt: skip

    bs = {k: r["summary"] for k, r in runs.items() if k.startswith("blocksize/")}
    if bs:
        out += ["## Block size, 16 vs 32 (same KV budget in token slots)", ""]
        rows = []

        def bs_key(k):  # blocksize/bs=16/rate=8/tokens=16384
            parts = dict(x.split("=") for x in k.split("/")[1:])
            return (-int(parts["tokens"]), float(parts["rate"]), int(parts["bs"]))

        for key in sorted(bs, key=bs_key):
            s = bs[key]
            parts = dict(x.split("=") for x in key.split("/")[1:])
            rows.append([parts["tokens"], parts["rate"], parts["bs"], f"{s['throughput_tok_s']:.1f}",
                         f"{s['itl_ms']['p50']:.1f} / {s['itl_ms']['p99']:.1f}", f"{s['peak_kv_allocated_mib']:.0f}",
                         f"{100 * s['kv_utilization']:.1f}%", s["max_concurrent"], s["stats"]["num_preemptions"]])  # fmt: skip
        out += [md_table(["KV budget (tokens)", "req/s", "Block size", "Throughput (tok/s)", "ITL p50 / p99 (ms)", "Peak KV in use (MiB)",
                          "Mean utilisation", "Max concurrent", "Preemptions"], rows), ""]  # fmt: skip

    pool = {k: r for k, r in runs.items() if k.startswith("pool/")}
    if pool:
        rate = next(iter(pool.values()))["rate"]
        out += [f"## Shrinking the KV budget (arrival rate {rate:g} req/s)", ""]
        rows = []
        for key in sorted(pool, key=lambda k: (-int(k.split("tokens=")[1]), k)):
            s, sysname = pool[key]["summary"], key.split("/")[1]
            tokens = int(key.split("tokens=")[1])
            st = s["stats"]
            pre = st.get("num_preemptions", 0)
            frac = share = "n/a"
            if sysname == "tokquay":
                frac = f"{100 * st['positions_discarded'] / st['positions_computed']:.1f}%"
                sl = s["stalls"]  # all prefill steps (recompute included): an upper bound on recompute's time cost
                share = f"{100 * sl['num_prefill_steps'] * sl['prefill_step_ms']['mean'] / 1e3 / s['duration_s']:.0f}%"
            rows.append([tokens, f"{s['config']['kv_reserved_mib']:.0f}", SHORT[sysname], f"{s['throughput_tok_s']:.1f}",
                         _ms(s["ttft_ms"]["p99"]), s["max_concurrent"], pre if sysname == "tokquay" else "n/a", frac, share])  # fmt: skip
        out += [md_table(["KV budget (token slots)", "MiB", "System", "Throughput (tok/s)", "TTFT p99 (ms)", "Max concurrent",
                          "Preemptions", "Positions recomputed", "Run time in prefill steps"], rows, (0, 2)),
                "",
                "*Positions recomputed* is the share of all token positions the model ran that were run a second time because "
                "preemption had discarded their K/V. *Run time in prefill steps* counts every prefill step, recomputation included, "
                "so it is an upper bound on what recomputation cost in time.",
                ""]  # fmt: skip

    repeats = {k: r["summary"] for k, r in runs.items() if "#" in k}
    if repeats:
        out += ["## Repeat runs (same configuration, run again: run-to-run noise)", ""]
        rows = []
        for key in sorted(repeats):
            base = _run(runs, key.split("#")[0])
            s = repeats[key]
            if base:
                rows.append([key.split("#")[0], f"{base['throughput_tok_s']:.1f}", f"{s['throughput_tok_s']:.1f}",
                             f"{_ms(base['ttft_ms']['p99'])} / {_ms(s['ttft_ms']['p99'])}",
                             f"{base['itl_ms']['p99']:.0f} / {s['itl_ms']['p99']:.0f}"])  # fmt: skip
        out += [md_table(["Run", "Throughput first (tok/s)", "second", "TTFT p99 first / second (ms)", "ITL p99 first / second (ms)"], rows), ""]
    health = [(k, r["summary"]["gpu"]) for k, r in sorted(runs.items()) if r["summary"].get("gpu")]
    if health:
        cap = meta.get("memory_fraction")
        out += [
            "## GPU memory health of every run",
            "",
            f"The CUDA caching allocator was capped at {cap:.0%} of VRAM. A run whose peak reserved memory approaches the "
            "card's total can be slowed by memory spill, so it is listed here next to the results it would affect."
            if cap
            else "The CUDA caching allocator was not capped.",
            "",
            md_table(["Run", "Peak allocated (MiB)", "Peak reserved (MiB)", "of total", "Allocator retries"],
                     [[k, f"{g['peak_allocated_mib']:.0f}", f"{g['peak_reserved_mib']:.0f}",
                       f"{100 * g['peak_reserved_mib'] / g['total_mib']:.0f}%", g["alloc_retries"]] for k, g in health]),
            "",
        ]  # fmt: skip
    return "\n".join(out)


# ------------------------------------------------------------------------------ plots
def _theme(name: str) -> dict:
    t = THEMES[name]
    plt.rcParams.update({
        "font.family": ["Segoe UI", "DejaVu Sans"], "font.size": 9.5,
        "figure.facecolor": t["surface"], "axes.facecolor": t["surface"], "savefig.facecolor": t["surface"],
        "text.color": t["ink2"], "axes.labelcolor": t["ink2"], "xtick.color": t["muted"], "ytick.color": t["muted"],
    })  # fmt: skip
    return t


def _style_axes(ax, t: dict) -> None:
    for side in ("top", "right", "left"):
        ax.spines[side].set_visible(False)
    ax.spines["bottom"].set_color(t["axis"])
    ax.spines["bottom"].set_linewidth(PX)
    ax.grid(axis="y", color=t["grid"], linewidth=PX, linestyle="-")  # solid hairlines, never dashed
    ax.set_axisbelow(True)
    ax.tick_params(axis="both", length=0, labelsize=9, pad=6)


def _line(ax, x, y, color, t: dict, **kw) -> None:
    ax.plot(x, y, color=color, linewidth=2 * PX, solid_capstyle="round", solid_joinstyle="round", marker="o",
            markersize=10 * PX, markerfacecolor=color, markeredgecolor=t["surface"], markeredgewidth=2 * PX, **kw)  # fmt: skip


def _legend_handles(t: dict, systems) -> list[Line2D]:
    return [Line2D([0], [0], color=t[s], linewidth=2 * PX, marker="o", markersize=8 * PX, markerfacecolor=t[s],
                   markeredgecolor=t["surface"], label=NAMES[s]) for s in systems]  # fmt: skip


def plot_throughput(sweep: dict, out: Path, theme: str) -> None:
    t = _theme(theme)
    fig, ax = plt.subplots(figsize=(8, 4.4), dpi=100)
    _style_axes(ax, t)
    rates = sorted(sweep["tokquay"])
    mean_out = sweep["tokquay"][rates[0]]["output_tokens"] / sweep["tokquay"][rates[0]]["requests"]
    ax.plot(rates, [r * mean_out for r in rates], color=t["muted"], linewidth=1.5 * PX)
    ax.annotate("offered load", (rates[-1], rates[-1] * mean_out), xytext=(10, 0), textcoords="offset points",
                va="center", color=t["ink2"], fontsize=9)  # fmt: skip
    for system in ("static", "tokquay"):
        y = [sweep[system][r]["throughput_tok_s"] for r in rates]
        _line(ax, rates, y, t[system], t)
        ax.annotate(f"{y[-1]:.0f} tok/s", (rates[-1], y[-1]), xytext=(10, 0), textcoords="offset points", va="center",
                    color=t["ink"], fontsize=9.5, fontweight="semibold")  # fmt: skip
    ax.set_xlim(rates[0] - 0.25, rates[-1] + 1.0)
    ax.set_ylim(0, None)
    ax.set_xticks(rates)
    ax.set_xlabel("Arrival rate (requests / second)", labelpad=8)
    ax.set_ylabel("Throughput (output tokens / second)", labelpad=8)
    ax.legend(handles=_legend_handles(t, ("tokquay", "static")), loc="upper left", frameon=False, labelcolor=t["ink2"], fontsize=9.5)
    fig.tight_layout()
    fig.savefig(out, dpi=200)
    plt.close(fig)


def plot_latency(sweep: dict, out: Path, theme: str) -> None:
    """TTFT and ITL, p50 and p99: four panels with their own axes (no dual-axis anywhere)."""
    t = _theme(theme)
    fig, axes = plt.subplots(2, 2, figsize=(8, 6.4), dpi=100, sharex=True)
    rates = sorted(sweep["tokquay"])
    panels = [("ttft_ms", "p50", "Time to first token, median (s)", 1e-3), ("ttft_ms", "p99", "Time to first token, p99 (s)", 1e-3),
              ("itl_ms", "p50", "Inter-token latency, median (ms)", 1.0), ("itl_ms", "p99", "Inter-token latency, p99 (ms)", 1.0)]  # fmt: skip
    for ax, (metric, q, title, scale) in zip(axes.flat, panels):
        _style_axes(ax, t)
        for system in ("static", "tokquay"):
            _line(ax, rates, [sweep[system][r][metric][q] * scale for r in rates], t[system], t)
        ax.set_title(title, loc="left", color=t["ink"], fontsize=10, fontweight="semibold", pad=10)
        ax.set_ylim(0, None)
        ax.set_xticks(rates)
    for ax in axes[1]:
        ax.set_xlabel("Arrival rate (requests / second)", labelpad=8)
    fig.legend(handles=_legend_handles(t, ("tokquay", "static")), loc="upper left", ncol=2, frameon=False, labelcolor=t["ink2"],
               fontsize=9.5, bbox_to_anchor=(0.06, 1.0))  # fmt: skip
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    fig.savefig(out, dpi=200)
    plt.close(fig)


def plot_budget(runs: dict, out: Path, theme: str) -> None:
    """Throughput as the KV memory budget shrinks, at one fixed arrival rate."""
    t = _theme(theme)
    fig, ax = plt.subplots(figsize=(8, 4.4), dpi=100)
    _style_axes(ax, t)
    series: dict[str, list[tuple[float, float]]] = {"tokquay": [], "static": []}
    for key, r in runs.items():
        if key.startswith("pool/"):
            s = r["summary"]
            series[key.split("/")[1]].append((s["config"]["kv_reserved_mib"], s["throughput_tok_s"]))
    for system in ("static", "tokquay"):
        pts = sorted(series[system])
        _line(ax, [p[0] for p in pts], [p[1] for p in pts], t[system], t)
        ax.annotate(f"{pts[0][1]:.0f}", pts[0], xytext=(-10, 0), textcoords="offset points", ha="right", va="center",
                    color=t["ink"], fontsize=9.5, fontweight="semibold")  # fmt: skip
    xs = sorted({p[0] for pts in series.values() for p in pts})
    ax.set_xscale("log")
    ax.set_xticks(xs)
    ax.set_xticklabels([f"{x:.0f}" for x in xs])
    ax.minorticks_off()
    ax.set_xlim(xs[0] * 0.65, xs[-1] * 1.3)
    ax.set_ylim(0, None)
    ax.set_xlabel("KV cache memory budget (MiB, log scale)", labelpad=8)
    ax.set_ylabel("Throughput (output tokens / second)", labelpad=8)
    ax.legend(handles=_legend_handles(t, ("tokquay", "static")), loc="upper left", frameon=False, labelcolor=t["ink2"], fontsize=9.5)
    fig.tight_layout()
    fig.savefig(out, dpi=200)
    plt.close(fig)


def report(store, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    img = out_dir / "img"
    img.mkdir(exist_ok=True)
    runs = store.data["runs"]
    (out_dir / "results.md").write_text(build_markdown(store), encoding="utf-8")
    print(f"wrote {out_dir / 'results.md'}")
    sweep = _sweep(runs)
    for theme in THEMES:
        if "tokquay" in sweep and "static" in sweep:
            plot_throughput(sweep, img / f"throughput_vs_rate_{theme}.png", theme)
            plot_latency(sweep, img / f"latency_vs_rate_{theme}.png", theme)
        if any(k.startswith("pool/") for k in runs):
            plot_budget(runs, img / f"throughput_vs_kv_budget_{theme}.png", theme)
    print(f"wrote plots to {img}")
